"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-76dq9!!c*j_+n-ia!o!im%#v6xs91m-bhe9ouwvw8owwpxu7g='

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accounts.apps.AccountsConfig',
    'home.apps.HomeConfig',
    'product_module.apps.ProductModuleConfig',
    'storages',
    'django_celery_beat',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'templates',
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

# TIME_ZONE = 'Asia/Tehran'
TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True #if it be false django uses server timezone and time


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'
#staticFiles_dirs is for setting global static files but for special app we need just static url
STATICFILES_DIRS=[
    BASE_DIR / 'static_files',
]

#media
MEDIA_URL='/media/'
MEDIA_ROOT=BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

#custom settings
AUTH_USER_MODEL='accounts.User'

#ARVAN CLOUD STORAGE

# STORAGES = {
#     "default": {
#         "BACKEND": "storages.backends.s3.S3Storage",
#         "OPTIONS": {
          
#         },
#     },
# } 

#for media files in arvan storages
#static
DEFAULT_FILE_STORAGE= 'storages.backends.s3boto3.S3Boto3Storage'

AWS_S3_FILE_OVERWRITE=False #this is for using one file twice and rename second one(overwrite name)
#dynamics
AWS_S3_ACCESS_KEY_ID = '268ed822-9a8f-4a49-97c3-f02c59e6c8ba' #AWS_ACCESS_KEY_ID
AWS_S3_SECRET_ACCESS_KEY = '6d381d76cb907ad57d8d100765e98577631599a7e81b97c70913e97602e058ba' #AWS_SECRET_ACCESS_KEY
AWS_S3_ENDPOINT_URL= 'https://s3.ir-tbz-sh1.arvanstorage.ir'

AWS_STORAGE_BUCKET_NAME= 'avalanch-django-shop' #in arvan cloud server must be unique this name
AWS_SEVICE_NAME= 's3' #this is not necessary for configing but it uses for geting data from clouds
AWS_LOCAL_STORAGE=f'{BASE_DIR}/aws/'
